### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by xLive** [gta191977649/MTA-SAMP-OBJ#2]
These files do not exist:
https://github.com/gta191977649/MTA-SAMP-OBJ/blob/2ce71101eaf43f3dd8c73d0ca901656d7951b30d/sampmap/meta.xml#L5-L14

**Comment by gta191977649** [comment]
Just removed the unused test maps now it should work independently, please check.

**Comment by xLive** [comment]
Yes, it's working now, thanks for the great tool!

I just found some other problems:
```[OBJ_MAT]: Error on model 11802, req txd: mp_gs_pooltiles,model_id: 14387, mat_index: 2
[OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
[OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
[OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
[OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
[OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
[OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
[OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
[OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
[OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
```
also, /testmap is missing it doesn't work.

**Comment by gta191977649** [comment]
That's probably due to some textures index is missing in the materials lookup table,i see what i can do about. 
By the way it should be `/maptest`, i made a mistake in docs gonna fix it soon.
That's for the report

**Comment by gta191977649** [comment]
> Yes, it's working now, thanks for the great tool!
> 
> I just found some other problems:
> 
> ```
> [OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
> [OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
> [OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
> [OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
> [OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
> [OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
> [OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
> [OBJ_MAT]: Error on model 1962, req txd: goldplate,model_id: 19076, mat_index: 1
> [OBJ_MAT]: Error on model 1942, req txd: metalwheel4_128,model_id: 7103, mat_index: 1
> ```
> 
> also, /testmap is missing it doesn't work.

That's probably due to some textures index is missing in the materials lookup table,i see what i can do about.
By the way the command should be `/maptest`, i made a mistake in docs gonna fix it soon.
That's for the report
